"use client";

import { useState } from "react";
import { ArrowLeft, CalendarDays, Check, Clock3, FileCheck2, Fingerprint, Home, LockKeyhole, QrCode, RadioTower, ShieldCheck, Smartphone, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

type Method="QR Code"|"Reconhecimento facial"|"Botão no aplicativo";
export default function MobileApp(){
 const[logged,setLogged]=useState(false);const[registered,setRegistered]=useState(false);const[method,setMethod]=useState<Method>("Botão no aplicativo");
 if(!logged)return <main className="mobile-stage"><section className="phone login-phone"><header><a href={`${basePath}/`}><ArrowLeft/></a><div className="mobile-brand"><span><RadioTower/></span><b>Ponto<em>Norte</em></b></div></header><div className="login-copy"><span className="login-symbol"><LockKeyhole/></span><h1>Acesse sua conta</h1><p>Use os dados enviados pela sua empresa.</p></div><form onSubmit={e=>{e.preventDefault();setLogged(true)}}><label>CPF ou e-mail<Input defaultValue="victor@cpusis.com.br"/></label><label>Senha<Input type="password" defaultValue="12345678"/></label><button type="button">Esqueci minha senha</button><Button type="submit">Entrar</Button></form><footer><ShieldCheck/><span>Seus registros são protegidos e vinculados ao seu dispositivo.</span></footer></section></main>;
 return <main className="mobile-stage"><section className="phone employee-app"><header className="mobile-top"><div className="mobile-brand"><span><RadioTower/></span><b>Ponto<em>Norte</em></b></div><span className="avatar">VS</span></header><div className="mobile-body"><p className="greeting">Olá, Victor</p><h1>Seu dia de trabalho</h1><section className="clock-card"><header><span>TERÇA-FEIRA, 8 SET</span><Badge/></header><time>08:42</time><p>Jornada: 08:00 às 18:00</p>{registered?<div className="registered"><Check/><span><b>Ponto registrado às 08:42</b><small>{method} · Sede CPUSIS</small></span></div>:<Dialog><DialogTrigger asChild><Button className="register-button"><Fingerprint/>Registrar ponto</Button></DialogTrigger><DialogContent className="method-dialog"><DialogHeader><DialogTitle>Como deseja registrar?</DialogTitle><DialogDescription>Sua empresa liberou estes métodos neste dispositivo.</DialogDescription></DialogHeader><div className="mobile-methods"><MethodButton icon={QrCode} title="QR Code" desc="Escanear código da empresa" onClick={()=>{setMethod("QR Code");setRegistered(true)}}/><MethodButton icon={Fingerprint} title="Reconhecimento facial" desc="Validar rosto e prova de vida" onClick={()=>{setMethod("Reconhecimento facial");setRegistered(true)}}/><MethodButton icon={Smartphone} title="Botão no aplicativo" desc="Registrar com confirmação" onClick={()=>{setMethod("Botão no aplicativo");setRegistered(true)}}/></div></DialogContent></Dialog>}</section><section className="today-card"><header><h2>Registros de hoje</h2><button>Ver espelho</button></header><div className="day-line"><span className="done"><Check/></span><p><b>Entrada</b><small>{registered?"08:42":"Ainda não registrada"}</small></p><time>{registered?"08:42":"—"}</time></div><div className="day-line muted"><span/><p><b>Início do intervalo</b><small>Previsto para 12:00</small></p><time>—</time></div><div className="day-line muted"><span/><p><b>Fim do intervalo</b><small>Previsto para 13:00</small></p><time>—</time></div><div className="day-line muted"><span/><p><b>Saída</b><small>Prevista para 18:00</small></p><time>—</time></div></section><section className="mobile-note"><ShieldCheck/><p><b>Localização confirmada</b><small>Você está dentro da área permitida pela empresa.</small></p></section></div><nav className="mobile-nav"><button className="active"><Home/><span>Início</span></button><button><Clock3/><span>Meus pontos</span></button><button><FileCheck2/><span>Comprovantes</span></button><button><UserRound/><span>Perfil</span></button></nav></section></main>
}
function Badge(){return <span className="online-badge"><i/>Online</span>}
function MethodButton({icon:Icon,title,desc,onClick}:{icon:React.ComponentType<{className?:string}>;title:string;desc:string;onClick:()=>void}){return <button onClick={onClick}><span><Icon/></span><p><b>{title}</b><small>{desc}</small></p></button>}
